spring:
  application:
    name: "str-consumer"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 2 #limitar o número de registros retornados em cada chamada ao poll(). default 500
#      fetch-min-size: 1
#      fetch-max-wait: 500
#      enable-auto-commit: true
#      auto-commit-interval: 1000

#controla o tempo máximo entre chamadas ao método poll().
#Se o consumidor não chamar poll() dentro desse intervalo, ele será considerado inativo
#e um reequilíbrio do grupo de consumidores será iniciado.
      max.poll.interval.ms: 1000 #default 300000

    topic:
      consumer: str-topic